/**
 * StateBean.java
 * JavaBean used to access the brennanstatesdata table in the CSD430 DB
 * 
 * Brennan Cheatwood
 * CSD430 - Module 7 - Project Part 2
 * 7/26/26
 */

package beans;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * StateBean
 * JavaBean used to access the brennanstatesdata table in the CSD430 DB.
 * Provides methods to retrieve all state IDs/names for a dropdown list,
 * and to retrieve a single full record by its primary key.
 */

public class StateBean {
	//DB connection details
	private static final String URL = "jdbc:mysql://localhost:3306/CSD430";
	private static final String USER = "student1";
	private static final String PASSWORD = "pass";
	
	//Bean properties representing one state record
	private int stateId;
	private String stateName;
	private String capital;
	private int population;
	private String region;
	private int yearAdmitted;
	
	//No-argument constructor required for javaBean convention
	public StateBean() {
	}
	
	//Standard getters and setters for bean properties
	public int getStateId() {
		return stateId;
	}
	
	public void setStateId(int stateId) {
		this.stateId = stateId;
	}
	
	public String getStateName() {
		return stateName;
	}
	
	public void setStateName(String stateName) {
		this.stateName = stateName;
	}
	
	public String getCapital() {
		return capital;
	}
	
	public void setCapital(String capital) {
		this.capital = capital;
	}
	
	public int getPopulation() {
		return population;
	}
	
	public void setPopulation(int population) {
		this.population = population;
	}
	
	public String getRegion() {
		return region;
	}
	
	public void setRegion(String region) {
		this.region = region;
	}
	
	public int getYearAdmitted() {
		return yearAdmitted;
	}
	
	public void setYearAdmitted(int yearAdmitted) {
		this.yearAdmitted = yearAdmitted;
	}
	
	
	
	/**
	 * Opens and returns a connection to the CSD430 DB
	 */
	private Connection getConnection() throws Exception {
		Class.forName("com.mysql.cj.jdbc.Driver");
		return DriverManager.getConnection(URL, USER, PASSWORD);
	}
	
	/**
	 * Retrieves every state_id and state_name pair from the table.
	 * used to populate the dropdown menu on the selection page.
	 * Each row is returned as a StateBean with only id and name set.
	 */
	public List<StateBean> getAllStateKeys() throws Exception {
		List<StateBean> keyList = new ArrayList<StateBean>();
		Connection conn = null;
		Statement stmt = null;
		ResultSet rs = null;
		
		
		try {
			conn = getConnection();
			stmt = conn.createStatement();
			rs = stmt.executeQuery("SELECT state_id, state_name FROM brennanstatesdata ORDER BY state_name");
			
			while (rs.next()) {
				StateBean row = new StateBean();
				row.setStateId(rs.getInt("state_id"));
				row.setStateName(rs.getString("state_name"));
				keyList.add(row);
			}
		} finally {
			if (rs != null) rs.close();
			if (stmt != null) stmt.close();
			if (conn != null) conn.close();
		}
		
		return keyList;
	}
	
	/**
	 * Retrieves a single full record from the table based on
	 * the primary key (state_id) chosen by the user
	 */
	public StateBean getStateById(int id) throws Exception {
		StateBean result = null;
		Connection conn = null;
		PreparedStatement ps = null;
		ResultSet rs = null;
		
		try {
			conn = getConnection();
			ps = conn.prepareStatement("SELECT * FROM brennanstatesdata WHERE state_id = ?");
			ps.setInt(1,  id);
			rs = ps.executeQuery();
			
			if (rs.next()) {
				result = new StateBean();
				result.setStateId(rs.getInt("state_id"));
				result.setStateName(rs.getString("state_name"));
				result.setCapital(rs.getString("capital"));
				result.setPopulation(rs.getInt("population"));
				result.setRegion(rs.getString("region"));
				result.setYearAdmitted(rs.getInt("year_admitted"));
			}
		} finally {
			if (rs != null) rs.close();
			if (ps != null) ps.close();
			if (conn != null) conn.close();
		}
		
		return result;
	}
	
	/**
     * Inserts a new state record into the brennanstatesdata table.
     * The primary key (state_id) is auto-generated by MySQL on insert,
     * so it is not supplied by the caller.
     */
    public void insertState(String stateName, String capital, int population,
                             String region, int yearAdmitted) throws Exception {
        Connection conn = null;
        PreparedStatement ps = null;

        try {
            conn = getConnection();
            String sql = "INSERT INTO brennanstatesdata (state_name, capital, population, region, year_admitted) VALUES (?, ?, ?, ?, ?)";
            ps = conn.prepareStatement(sql);
            ps.setString(1, stateName);
            ps.setString(2, capital);
            ps.setInt(3, population);
            ps.setString(4, region);
            ps.setInt(5, yearAdmitted);
            ps.executeUpdate();
        } finally {
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        }
    }

    /**
     * Retrieves every full record from the table, used to display
     * all states after a new record has been added.
     */
    public List<StateBean> getAllStates() throws Exception {
        List<StateBean> allStates = new ArrayList<StateBean>();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM brennanstatesdata ORDER BY state_id");

            while (rs.next()) {
                StateBean row = new StateBean();
                row.setStateId(rs.getInt("state_id"));
                row.setStateName(rs.getString("state_name"));
                row.setCapital(rs.getString("capital"));
                row.setPopulation(rs.getInt("population"));
                row.setRegion(rs.getString("region"));
                row.setYearAdmitted(rs.getInt("year_admitted"));
                allStates.add(row);
            }
        } finally {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (conn != null) conn.close();
        }

        return allStates;
    }
    
    /**
     * Updates an existing state record identified by its primary key (state_id).
     * All fields except the key are updated with the new values provided.
     */
    
    public void updateStateRecord(int id, String stateName, String capital, int population,
    		String region, int yearAdmitted) throws Exception {
    	Connection conn = null;
    	PreparedStatement ps = null;
    	
    	try {
    		conn = getConnection();
    		String sql = "UPDATE brennanstatesdata SET state_name = ?, capital = ?, population = ?, region = ?, year_admitted = ? WHERE state_id = ?";
    		ps = conn.prepareStatement(sql);
    		ps.setString(1, stateName);
    		ps.setString(2, capital);
    		ps.setInt(3, population);
    		ps.setString(4, region);
    		ps.setInt(5, yearAdmitted);
    		ps.setInt(6, id);
    		ps.executeUpdate();
    	} finally {
    		if (ps != null) ps.close();
    		if (conn != null) conn.close();
    	}
    }
	
	
}