<%-- ================================================
     california.jsp
     Author: Brennan Cheatwood
     Date: 6/21/26
     CSD430 - ServerSide Development
     
     Description: JSP page for my California road trip
     data. Uses scriptlets for Java code and keeps all
     HTML tags outside of them. Pulls in an external
     CSS file for styling.
     ================================================ --%>

<%-- Page directive — sets the language and character encoding --%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>California Road Trip</title>

    <%-- Linking the external CSS file — this is just HTML so it stays outside the scriptlet --%>
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>

    <%-- Page header — plain HTML, no Java needed here --%>
    <header>
        <h1>California Road Trip</h1>
        <p class="subtitle">
            A personal data record of my road trip through California:
            from the Nevada border to the Pacific Coast Highway and beyond.
        </p>
    </header>

    <main>

        <%-- ================================================
             SCRIPTLET #1 — Setting up the data as arrays.
             I'm using three String arrays to hold my 5 stops,
             one array per field. The scriptlet tags (<% %>)
             wrap the Java code so it doesn't mix with the HTML.

             Fields per record:
               - Location name
               - Region / type of stop
               - What happened there
             ================================================ --%>
        <%
            // The name of each place I stopped at (Field 1)
            String[] locations = {
                "Chilcoot-Vinton",
                "Gualala",
                "San Francisco to Monterey (CA-1 / PCH)",
                "Bakersfield",
                "Needles"
            };

            // The region and county for each stop (Field 2)
            String[] regions = {
                "Northern CA, Plumas County, CA/NV Border",
                "Northern California Coast, Mendocino County",
                "Central California Coast, Highway 1",
                "Central Valley, Kern County",
                "Inland Desert, San Bernardino County"
            };

            // A short description of what was notable about each stop (Field 3)
            String[] experiences = {
                "Camped at a campground right on the California-Nevada state border. Quiet, scenic, and a great way to start the trip.",
                "Drove out to the coast and really loved this small town. Great cliffs, ocean views, and a really chill atmosphere.",
                "Drove PCH south from San Francisco all the way down to Monterey. Saw a ton of sea lions along the way.",
                "Passed through on the drive south. Big agricultural and oil city in the middle of the San Joaquin Valley.",
                "Our van broke down here in the middle of summer heat. We ended up stuck for 4 days before renting a U-Haul and driving to Phoenix to fly home."
            };

            // Storing the length so I can reuse it later
            int totalRecords = locations.length;
        %>

        <%-- Table heading and description — HTML only, no scriptlet --%>
        <h2>Road Trip Stops: Data Table</h2>
        <p class="section-desc">
            Each row is one stop from my California road trip. The rows are
            generated by a Java loop in a scriptlet below.
        </p>

        <%-- HTML table structure — tags stay outside the scriptlets --%>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Location</th>
                    <th>Region / Type of Stop</th>
                    <th>Notable Experience</th>
                </tr>
            </thead>
            <tbody>

                <%-- ================================================
                     SCRIPTLET #2 — Loop through the arrays to build
                     the table rows. The for loop is inside the scriptlet
                     but the actual <tr> and <td> tags are outside it,
                     which is what the assignment requires.
                     ================================================ --%>
                <%
                    for (int i = 0; i < totalRecords; i++) {
                %>
                        <%-- <tr> and <td> tags are outside the scriptlet --%>
                        <tr>
                            <td><%= i + 1 %></td>
                            <td><%= locations[i] %></td>
                            <td><%= regions[i] %></td>
                            <td><%= experiences[i] %></td>
                        </tr>
                <%
                    } // end for loop
                %>

            </tbody>
        </table>

        <%-- Field descriptions — explains what each column means --%>
        <div class="legend">
            <strong>Field Descriptions:</strong>
            <ul>
                <li><strong>Location:</strong> The name of the city, town, or area I visited.</li>
                <li><strong>Region / Type of Stop:</strong> The broader area and county the location is in.</li>
                <li><strong>Notable Experience:</strong> A short note on what stood out or happened at that stop.</li>
            </ul>
        </div>

        <%-- ================================================
             SCRIPTLET #3 — Using a JSP expression to print
             the total record count inside the summary paragraph.
             The <%= %> tag outputs a value directly into the HTML.
             ================================================ --%>
        <h2>Trip Summary</h2>
        <p class="section-desc">
            This table has <strong><%= totalRecords %> stops</strong> from my California road trip.
            We started near the Nevada border, drove west to the coast, followed PCH down
            through San Francisco and Monterey, then cut inland through Bakersfield. The trip
            ended with our van breaking down in Needles before we took a U-Haul to Phoenix
            and flew back home to Knoxville.
        </p>

    </main>

    <%-- Page footer --%>
    <footer>
        Created by Brennan Cheatwood for CSD430.
        California Road Trip Data created with JSP Scriptlets and External CSS (styles.css)
    </footer>

</body>
</html>
